import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import Navbar from "./components/layout/navbar/navbar";
import { twMerge } from "tailwind-merge";
import AppWrapper from "@/app/store/provider";
import CustomNextUIProvider from "./components/providers/NextUI";
import AuthModal from "./components/ui/modal";

const ibm = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(ibm.style.fontFamily, "bg-background min-h-screen")}
      >
        <AppWrapper>
          <Navbar />
          <CustomNextUIProvider>
            {children}
            <AuthModal />
          </CustomNextUIProvider>
        </AppWrapper>
      </body>
    </html>
  );
}
